apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountservice
spec:
  selector:
    matchLabels:
      app: accountservice
  template:
    metadata:
      labels:
        app: accountservice
        app.kubernetes.io/version: "1.0.xx"
    spec:
      containers:
        - name: accountservice
          image: europe-docker.pkg.dev/dynatrace-demoability/docker/easytrade/accountservice:d863a2e
          ports:
            - containerPort: 8080
          env:
            - name: MANAGER_HOSTANDPORT
              value: "manager:80"
            - name: PROXY_PREFIX
              value: "accountservice"
            - name: "DT_RELEASE_VERSION"
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/version']
            - name: "DT_RELEASE_PRODUCT"
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app']
            - name: "DT_RELEASE_STAGE"
              value: "LABXX"
            - name: "DT_RELEASE_BUILD_VERSION"
              value: "09-02-2024"
          resources:
            requests:
              cpu: 150m
              memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: accountservice
spec:
  type: ClusterIP
  selector:
    app: accountservice
  ports:
    - name: http
      port: 8080
      targetPort: 8080
