apiVersion: dynatrace.com/v1beta1
kind: DynaKube
metadata:
  name: $CLUSTER
  namespace: dynatrace
spec:
  apiUrl: $DT_TENANT_URL/api
  tokens: dynakube
  networkZone: $CLUSTER
  #namespaceSelector:
  #  matchLabels:
  #    monitoring: dynatrace
  oneAgent:
    classicFullStack:
    #cloudNativeFullStack:
      image: ""
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
      args:
        - --set-host-group=$CLUSTER
      env:
        - name: ONEAGENT_ENABLE_VOLUME_STORAGE
          value: "true"
  activeGate:
    capabilities:
      - routing
      - kubernetes-monitoring
      - dynatrace-api
    image: ""
    group: $CLUSTER
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1.5Gi
