apiVersion: dynatrace.com/v1beta5
kind: DynaKube
metadata:
  name: $CLUSTER
  namespace: dynatrace
  annotations:
    feature.dynatrace.com/k8s-app-enabled: "true"
    feature.dynatrace.com/injection-readonly-volume: "true"
spec:
  apiUrl: $DT_TENANT_URL/api
  tokens: "dynakube"
  networkZone: $CLUSTER
  metadataEnrichment:
    enabled: true
  #namespaceSelector:
  #  matchLabels:
  #    monitoring: dynatrace
  oneAgent:
    hostGroup: $CLUSTER
    cloudNativeFullStack:
    #classicFullStack:
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
      args:
        - --set-host-tag=dt.cost.costcenter=$CLUSTER
      env:
        - name: ONEAGENT_ENABLE_VOLUME_STORAGE
          value: "true"
  activeGate:
    capabilities:
      - routing
      - kubernetes-monitoring
      - dynatrace-api
    image: ""
    group: $CLUSTER
    resources:
      requests:
        cpu: 500m
        memory: 1.5Mi
      limits:
        cpu: 1000m
        memory: 2Gi
    tolerations:
     - effect: NoSchedule
       operator: Exists
